name: lhens_app
description: "LH EnS Flutter App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  retrofit: ^4.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  go_router: ^14.6.1
  flutter_svg: ^2.0.10
  shared_preferences: ^2.3.3 # 캐시 저장용
  flutter_screenutil: ^5.7.0 # font정교하게 dpi, 폰트 스케일 등 고려하여
  flutter_secure_storage: ^9.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^9.1.7
  riverpod_generator: ^2.4.0
  freezed: ^2.4.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/tabs/
    - assets/icons/features/
    - assets/illustrations/
    - assets/images/
    - assets/logos/
    - assets/image/
    - assets/image/home/
    - assets/image/menu/
    - assets/image/mypage/
    - assets/image/common/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300

    - family: TheJamsil
      fonts:
        - asset: assets/fonts/TheJamsil/The Jamsil OTF 1 Thin.otf
          weight: 100
        - asset: assets/fonts/TheJamsil/The Jamsil OTF 2 Light.otf
          weight: 300
        - asset: assets/fonts/TheJamsil/The Jamsil OTF 3 Regular.otf
          weight: 400
        - asset: assets/fonts/TheJamsil/The Jamsil OTF 4 Medium.otf
          weight: 500
        - asset: assets/fonts/TheJamsil/The Jamsil OTF 5 Bold.otf
          weight: 700
        - asset: assets/fonts/TheJamsil/The Jamsil OTF 6 ExtraBold.otf
          weight: 800

flutter_gen:
  integrations:
    flutter_svg: true
